# Generated by Django 3.1.4 on 2022-10-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_auto_20221001_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
