# Generated by Django 3.1.4 on 2022-10-02 08:16

import ckeditor_uploader.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20221001_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
